# Policy for app
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: data-pipeline-api-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: data-pipeline-api
  policyTypes:
  - Ingress
  - Egress

  # Kto może się połączyć --> 
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8080
  
  # scalping metryk
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
    ports:
    - protocol: TCP
      port: 8080

  # Gdzie może się łączyć --> 
  egress:
  # redis
  - to:
    - podSelector:
        matchLabels:
           app.kubernetes.io/instance: redis
    ports:
    - protocol: TCP
      port: 6379

  - to:
    - podSelector:
        matchLabels:
           app.kubernetes.io/instance: postgresql
    ports:
    - protocol: TCP
      port: 5432

  # dns
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53

  # internet --> https
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.0.0.0/8      # Blokuj prywatne IP
        - 172.16.0.0/12
        - 192.168.0.0/16
    ports:
    - protocol: TCP
      port: 443