# NetworkPolicy dla Redis
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: redis
  policyTypes:
  - Ingress
  - Egress

  # app może się łączyć z redisem
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: data-pipeline-api
    ports:
    - protocol: TCP
      port: 6379

  # redis -> dns
  egress:
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: UDP
      port: 53