apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grafana.fullname" . }}-datasources
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: grafana
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
    {{- range .Values.datasources }}
    - name: {{ .name }}
      type: {{ .type }}
      url: {{ .url }}
      access: {{ .access }}
      isDefault: {{ .isDefault }}
    {{- end }}