apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: grafana
type: Opaque
stringData:
  admin-password: {{ .Values.adminPassword | default "changeme" | quote }}