name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
      - develop

env:
  PROJECT_ID: gcp-devops-pipelien-kamil
  REGION: europe-central2
  CLUSTER_NAME: devops-cluster
  REPOSITORY: docker-repo
  IMAGE: data-pipeline-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Google Auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker
      run: gcloud auth configure-docker europe-central2-docker.pkg.dev --quiet

    - name: Build Docker image
      run: |
        docker build -t europe-central2-docker.pkg.dev/gcp-devops-pipelien-kamil/docker-repo/data-pipeline-api:${{ github.sha }} ./app
        docker tag europe-central2-docker.pkg.dev/gcp-devops-pipelien-kamil/docker-repo/data-pipeline-api:${{ github.sha }} europe-central2-docker.pkg.dev/gcp-devops-pipelien-kamil/docker-repo/data-pipeline-api:latest

    - name: Push Docker image
      run: |
        docker push europe-central2-docker.pkg.dev/gcp-devops-pipelien-kamil/docker-repo/data-pipeline-api:${{ github.sha }}
        docker push europe-central2-docker.pkg.dev/gcp-devops-pipelien-kamil/docker-repo/data-pipeline-api:latest

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: devops-cluster
        location: europe-central2-a

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
   
    - name: Deploy Monitoring Stack
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update
        
        helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
          --namespace monitoring \
          --create-namespace \
          --set grafana.adminPassword="${{ secrets.GRAFANA_PASSWORD }}" \
          --set prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues=false

    - name: Verify monitoring deployment
      run: |
        kubectl get pods -n monitoring
        kubectl get svc -n monitoring

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/data-pipeline-api \
          data-pipeline-api=${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:latest \
          -n default
        
        kubectl rollout status deployment/data-pipeline-api -n default --timeout=5m